name: Frontend CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure SSH
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
        env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.PRIVATE_KEY}}
            SSH_HOST: ${{ secrets.HOST }}
      - name: SSH deploy $GITHUB_REF branch version
        run: |
              ssh staging 'cd liv'
              ssh staging 'rm -r dist'
              ssh staging 'git fetch'
              ssh staging 'git checkout $GITHUB_REF'
              ssh staging 'git pull'
              ssh staging 'npm install'
              ssh staging 'npm run build'

  restart:
    needs: setup
    runs-on: ubuntu-latest
    steps:
        - name: Configure SSH
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
          env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.PRIVATE_KEY}}
            SSH_HOST: ${{ secrets.HOST }}
        - name: SSH restart server 
          run: ssh staging 'sudo reboot'
